### PR TITLE
Fix Packages Building Error

### PR DESCRIPTION
**Pull request by oradwanomar**

### CODE REVIEW

**Review by ahmdyasser — CHANGES_REQUESTED** [review]
files with .pbxproj and .resolved extensions should be added to the .gitignore file

**Comment by ahmdmhasn** [comment]
> files with .pbxproj and .resolved extensions should be added to the .gitignore file

`.resolved` only should be ignored.

**Comment by ahmdmhasn** [comment]
I think we need to hold it until #7 is merged 👌

**Comment by ahmdyasser** [comment]
@ahmdmhasn  This PR should be edited or it's okay to be merged? since the #7 is merged successfully.

**Review by ahmdyasser — APPROVED** [review]

**Review by HebaMad — APPROVED** [review]
👏

**Pull request merged**
