### PR TITLE
feat: Add product details view controller and view model 🤺 (#56)

### PR DESCRIPTION
**Pull request by ahmdyasser**
* Add product details view controller and view model

* Add scroll view and stack view

* Add views group

* Add dummy views

### CODE REVIEW

**Comment by ahmdyasser** [comment]
@ahmdmhasn  this should be merged to ui_design so we can work on that branch right?

**Comment by ahmdmhasn** [comment]
@ahmdyasser This should be either merged locally or use GitHub update branch instead.

**Comment by ahmdmhasn** [comment]
@ahmdyasser Any update? 😁

**Comment by ahmdyasser** [comment]
> @ahmdyasser Any update? 😁

@ahmdmhasn تطبخ في صمت 🤌

**Comment by ahmdmhasn** [comment]
@ahmdyasser 
You don't need a pull request to merge `develop` to any branch 😁

**Pull request merged**
